

services:
  # Development environment với tất cả tools
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
      - "3002:3000"
      - "22:22"  # SSH port
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/workspace/src
      - PYTHONUNBUFFERED=1
      - REACT_APP_API_URL=http://localhost:8001
    stdin_open: true
    tty: true
    command: /usr/local/bin/dev-start
    networks:
      - flight-network

  # Production backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    networks:
      - flight-network

  # Production frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3003:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - flight-network

networks:
  flight-network:
    driver: bridge 