services:
  - type: web
    name: flight-backend
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: cd src && uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PYTHON_VERSION
        value: "3.8.18" 