name: Test Air Traffic Control System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test backend imports
      run: |
        cd src
        python -c "import api; print('✅ Backend import successful')"
        python -c "from models.airspace import Airspace; print('✅ Airspace model import successful')"
        python -c "from models.flight import Flight; print('✅ Flight model import successful')"
        python -c "from algorithms.conflict_detection import detect_conflicts; print('✅ Conflict detection import successful')"
        python -c "from algorithms.pathfinding import a_star_search; print('✅ Pathfinding import successful')"
    
    - name: Test data loading
      run: |
        cd src
        python debug_load.py
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm run test:ci
    
    - name: Test frontend build
      run: |
        cd frontend
        CI=false npm run build
        echo "✅ Frontend build successful" 